# This is a basic workflow that is manually triggered

name: Manual scan-iac-checkov

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
   
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v1
     
     - uses: actions/setup-python@v2

     - name: Install checkov and scan environment(s)
     - run: |
        
        #!/bin/bash
        set -e

        pip install checkov 

        checkov -d .


