# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: scan-iac-checkov
on: [pull_request]

jobs:
  install-tools:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      - name : Install Python
        uses: actions/setup-python@v2

      - name: Install checkov and scan environment(s)
        run: |

          #!/bin/bash
          set -e

          pip install checkov 

          checkov -d .

      
        
